apiVersion: v1
kind: Pod
metadata:
  name: pod-sa
  labels:
    app: myapp
    tier: frontend
  annotations:
    chen.yongyong/created-by: "cluster sa myadmin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports:
    - name: web
      containerPort: 80
  serviceAccountName: myadmin
