apiVersion: v1
kind: Pod
metadata: 
  name: node-affinity
  namespace: default
  labels:
    app: myapp
    tier: fronted
spec:
  containers:
  - name: mypp
    image: ikubernetes/myapp:v1
  affinity:
    nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - foo
            - bar
