apiVersion: v1
kind: Pod
metadata: 
  name: pod-first
  namespace: default
  labels:
    app: myapp
    tier: fronted
spec:
  containers:
  - name: mypp
    image: ikubernetes/myapp:v1
---
apiVersion: v1
kind: Pod
metadata: 
  name: pod-second
  namespace: default
  labels:
    app: db
    tier: db
spec:
  containers:
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sh","-c","sleep 3600"]
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - {"key": app, operator: In, values: ["myapp"]}
        topologyKey: kubernetes.io/hostname
