apiVersion: v1
kind: Pod
metadata: 
  name: node-affinity
  namespace: default
  labels:
    app: myapp
    tier: fronted
spec:
  containers:
  - name: mypp
    image: ikubernetes/myapp:v1
  affinity:
    nodeAffinity:
       preferredDuringSchedulingIgnoredDuringExecution:
       - preference: 
          matchExpressions:
          - key: zone
            operator: In
            values:
            - foo
            - barddd
         weight: 60
