apiVersion: v1
kind: Pod
metadata: 
  name: pod-daemon
  namespace: default
  labels:
    app: myapp
    tier: fronted
spec:
  containers:
  - name: mypp
    image: ikubernetes/stress-ng
    command: ["/usr/bin/stress-ng", "-c 1", "--metrics-brief"] 
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 512Mi
